### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by Brawl345** [WiiDatabase/RiiTag-Next#5]
The database migration has to be done for migrating the JSON data files into the MySQL database. I have opened a WIP `feature/migration` branch but I don't know when I will be finished with it. This issue is here to keep track of this.

- [x] Migrate users
- [ ] Migrate stuff from the *.db files (coins are duplicated I think...?)
- [ ] Migrate playlog
- [ ] Maybe some more stuff that I forgot

**Comment by TheShadowEevee** [comment]
I can confirm that coin count is duplicated between the `coindb` and the .json files based on observation and code reading. The coin data is saved to the `coindb` when the games leaderboard is updated

I'm not sure why this design choice was made exactly but probably to keep the json files for the tag and the db for future leaderboards. IMO user changeable information should be in the json and more server controlled info (coins, gameplay) should be in a db in the original setup; I'm not sure how storage is here though as I haven't looked at that myself.

**Comment by TheShadowEevee** [comment]
I myself can't think of anything else that's not yet on your checklist, to add to my comment above
