### ISSUE TITLE
Website Currently down

### ISSUE THREAD

**Issue by prestonstone2004** [WiiDatabase/RiiTag-Next#58]
Internal server error
![Screenshot_20231117-014240](https://github.com/RiiConnect24/RiiTag-Next/assets/69037877/c64d0a44-73b2-4965-8bb8-b9d90e6decd7)
![Screenshot_20231117-034450](https://github.com/RiiConnect24/RiiTag-Next/assets/69037877/3cfa5a9f-877a-400a-ac46-60f98cc85702)

**Comment by larsenv** [comment]
Unfortunately RiiTag has been going down all the time because of an issue with a node module called client-only continuously being removed, I will try to ensure it gets fixed. Thank you.
